services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./../../nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ../../../front
      dockerfile: Dockerfile.dev
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ../../../front/textcare:/app
      - /app/node_modules
