FROM node:18-alpine
WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY textcare/package*.json ./

RUN npm ci

COPY textcare/ .

EXPOSE 3000

CMD ["npm", "run", "dev"]
